name: Main

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        run: |
          echo "is_sh_ver=$(cat v2ray.sh | grep -oP 'is_sh_ver=\K.*')" >> $GITHUB_ENV
          echo "old=$(git tag | tail -n1)" >> $GITHUB_ENV
      - name: Create zip archive
        run: zip -9vr code.zip . -x .\* .git\*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: code.zip
          tag_name: ${{ env.is_sh_ver }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
